version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build
# See notes below.
jobs:
  build:
    docker:
      - image: circleci/node.13.8.0
    steps:
      - checkout
      - run:
          name: "echo env var"
          command: |
            echo $MY_NAME