version: 2.1
# See notes below.
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  print_my_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
        - run: MY_NAME
workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_my_name 