version: 2.1
# See notes below.
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  build:
    docker:
      - image: circleci/node.13.8.0
    steps:
      - checkout
      - run:
          name: "echo env var"
          command: |
            echo $MY_NAME
welcome:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - test-env-vars:
          jobs:
            - build