version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build
# See notes below.
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo env var"
          command: |
            echo $MY_NAME